[build]
  publish = "dist/sakai-ng/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Redirection pour SPA - toutes les routes doivent pointer vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/bpmn-font/font/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.eot"
  [headers.values]
    Content-Type = "application/vnd.ms-fontobject"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
